{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.netflow;
  defaultConfig = import ./config.nix { inherit pkgs; };
  configFile = pkgs.writeText "netflow-config.yaml" (''
    # netflow config - generated by NixOS module
    port: ${builtins.toString cfg.settings.backendPort}
    secret: "${cfg.settings.apiSecret}"
    redirPort: ${builtins.toString cfg.settings.redirPort}
    dnsPort: ${builtins.toString cfg.settings.dnsPort}
    mixedPort: ${builtins.toString cfg.settings.mixedPort}
    proxyMode: ${cfg.settings.proxyMode}
    runMode: ${cfg.settings.runMode}
    tunEnabled: ${if cfg.settings.tunEnabled then "true" else "false"}
    lanProxy: ${if cfg.settings.lanProxy then "true" else "false"}
    ipv6Proxy: ${if cfg.settings.ipv6Proxy then "true" else "false"}
    mihomoPath: ${cfg.settings.mihomoPath}
    mihomoData: ${cfg.settings.mihomoData}
    configDir: ${cfg.settings.configDir}
    ossUrl: "${cfg.settings.ossUrl}"
  '');
  # netflow binary 实际上从 /etc/config/netflow (UCI 格式) 读 oss_url / api_port 等
  # (它的错误日志直接说"检查 UCI backend_port")。NixOS 没 UCI 系统,得在 bind mount
  # 里把 build-time 生成的 UCI 文件投到 /etc/config/netflow。
  uciFile = pkgs.writeText "netflow-config-uci" ''
    config netflow 'config'
    	option enable '1'
    	option config_path '/etc/netflow/config.yaml'
    	option config_dir '${cfg.settings.configDir}'
    	option mihomo_path '${cfg.settings.mihomoPath}'
    	option api_port '${builtins.toString cfg.settings.apiPort}'
    	option api_secret '${cfg.settings.apiSecret}'
    	option backend_port '${builtins.toString cfg.settings.backendPort}'
    	option redir_port '${builtins.toString cfg.settings.redirPort}'
    	option dns_port '${builtins.toString cfg.settings.dnsPort}'
    	option mixed_port '${builtins.toString cfg.settings.mixedPort}'
    	option proxy_mode '${cfg.settings.proxyMode}'
    	option run_mode '${cfg.settings.runMode}'
    	option tun_enabled '${if cfg.settings.tunEnabled then "1" else "0"}'
    	option lan_proxy '${if cfg.settings.lanProxy then "1" else "0"}'
    	option ipv6_proxy '${if cfg.settings.ipv6Proxy then "1" else "0"}'
    	option oss_url '${cfg.settings.ossUrl}'

    config v2board 'v2board'
    	option api_url ''''
    	option email ''''
    	option token ''''
    	option auto_subscribe '1'
    	option last_login_time ''''
    	option last_subscribe_time ''''
  '';
in
{
  options.services.netflow = {
    enable = lib.mkEnableOption "netflow proxy client";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.netflow;
      description = "Netflow package";
    };

    settings = lib.mkOption {
      type = lib.types.submodule {
        options = {
          apiPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.apiPort;
            description = "API control port";
          };
          apiSecret = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.apiSecret;
            description = "API secret";
          };
          backendPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.backendPort;
            description = "Backend API port for LuCI frontend";
          };
          redirPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.redirPort;
            description = "Redir port";
          };
          dnsPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.dnsPort;
            description = "DNS port";
          };
          mixedPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.mixedPort;
            description = "Mixed proxy port";
          };
          proxyMode = lib.mkOption {
            type = lib.types.enum [
              "rule"
              "whitelist"
              "global"
            ];
            default = defaultConfig.proxyMode;
            description = "Proxy mode";
          };
          runMode = lib.mkOption {
            type = lib.types.enum [
              "fake-ip"
              "redir"
            ];
            default = defaultConfig.runMode;
            description = "Run mode";
          };
          tunEnabled = lib.mkOption {
            type = lib.types.bool;
            default = defaultConfig.tunEnabled;
            description = "Enable TUN mode";
          };
          lanProxy = lib.mkOption {
            type = lib.types.bool;
            default = defaultConfig.lanProxy;
            description = "Proxy LAN";
          };
          ipv6Proxy = lib.mkOption {
            type = lib.types.bool;
            default = defaultConfig.ipv6Proxy;
            description = "Proxy IPv6";
          };
          mihomoPath = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.mihomoPath;
            description = "Mihomo binary path";
          };
          mihomoData = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.mihomoData;
            description = "Mihomo data directory (geoip, geosite)";
          };
          configDir = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.configDir;
            description = "Config directory";
          };
          ossUrl = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.ossUrl;
            description = "OSS subscription URL";
          };
        };
      };
      default = { };
      description = "Netflow settings";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.mihomo ];

    # 系统用户(无 home / 无 shell / 无 password)
    users.users.netflow = {
      isSystemUser = true;
      group = "netflow";
      description = "netflow proxy client";
    };
    users.groups.netflow = { };

    # systemd StateDirectory=netflow 自动管 /var/lib/netflow,这里只确保目录存在
    systemd.tmpfiles.rules = [
      "d /var/lib/netflow 0755 netflow netflow -"
    ];

    systemd.services.netflow = {
      description = "netflow proxy client";
      wantedBy = [ "multi-user.target" ];
      conflicts = [ "singbox.service" "singbox-backup.service" ];
      after = [ "systemd-tmpfiles-setup.service" ];

      # preStart 在 service mount namespace + BindPaths 下运行:
      # namespace 里 /var/lib/netflow = host 上 /var/lib/netflow(BindPaths 只把 host 路径
      # 绑到 namespace 里的 /etc/netflow,/var/lib/netflow 本身仍指向 host)。
      preStart = ''
        set -e
        if [ ! -f /var/lib/netflow/config.yaml ]; then
          install -m 0644 -o netflow -g netflow ${configFile} /var/lib/netflow/config.yaml
        fi
        if [ ! -s /var/lib/netflow/.dev_salt ]; then
          ${pkgs.coreutils}/bin/head -c 32 /dev/urandom \
            | ${pkgs.coreutils}/bin/od -An -tx1 | ${pkgs.gnused}/bin/sed 's/ //g' \
            > /var/lib/netflow/.dev_salt
          chmod 600 /var/lib/netflow/.dev_salt
          chown netflow:netflow /var/lib/netflow/.dev_salt
        fi
      '';

      serviceConfig = {
        Type = "simple";
        Restart = "always";
        RestartSec = "5";
        # 整个 /var/lib/netflow 映射为 namespace 里的 /etc/netflow
        # 另外把 build-time 的 UCI 文件 bind 到 /etc/config/netflow(binary 主要从这里读 oss_url)
        StateDirectory = "netflow";
        BindPaths = [
          "/var/lib/netflow:/etc/netflow"
          "${uciFile}:/etc/config/netflow"
        ];
        # 降权跑
        User = "netflow";
        Group = "netflow";
        # Hardening
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        # 透明代理需要 NET cap
        CapabilityBoundingSet = [
          "CAP_NET_ADMIN"
          "CAP_NET_BIND_SERVICE"
          "CAP_NET_RAW"
        ];
        AmbientCapabilities = [
          "CAP_NET_ADMIN"
          "CAP_NET_BIND_SERVICE"
          "CAP_NET_RAW"
        ];
        # 写白名单:只允许写 /var/lib/netflow(/tmp 走 PrivateTmp,/etc 被 strict 锁)
        ReadWritePaths = [ "/var/lib/netflow" ];
        ExecStart = "${cfg.package}/bin/netflow";
      };
    };
  };
}
