{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.netflow;
  # 默认值从 pkgs/netflow/config.nix 引入(集中维护)
  defaultConfig = import ./config.nix { inherit pkgs; };
  configFile = pkgs.writeText "netflow-config.yaml" (''
    # netflow config - generated by NixOS module
    port: ${builtins.toString cfg.settings.backendPort}
    secret: "${cfg.settings.apiSecret}"
    redirPort: ${builtins.toString cfg.settings.redirPort}
    dnsPort: ${builtins.toString cfg.settings.dnsPort}
    mixedPort: ${builtins.toString cfg.settings.mixedPort}
    proxyMode: ${cfg.settings.proxyMode}
    runMode: ${cfg.settings.runMode}
    tunEnabled: ${if cfg.settings.tunEnabled then "true" else "false"}
    lanProxy: ${if cfg.settings.lanProxy then "true" else "false"}
    ipv6Proxy: ${if cfg.settings.ipv6Proxy then "true" else "false"}
    mihomoPath: ${cfg.settings.mihomoPath}
    mihomoData: ${cfg.settings.mihomoData}
    configDir: ${cfg.settings.configDir}
    ossUrl: "${cfg.settings.ossUrl}"
  '');
in
{
  options.services.netflow = {
    enable = lib.mkEnableOption "netflow proxy client";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.netflow;
      description = "Netflow package";
    };

    settings = lib.mkOption {
      type = lib.types.submodule {
        options = {
          apiPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.apiPort;
            description = "API control port";
          };
          apiSecret = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.apiSecret;
            description = "API secret";
          };
          backendPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.backendPort;
            description = "Backend API port for LuCI frontend";
          };
          redirPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.redirPort;
            description = "Redir port";
          };
          dnsPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.dnsPort;
            description = "DNS port";
          };
          mixedPort = lib.mkOption {
            type = lib.types.port;
            default = defaultConfig.mixedPort;
            description = "Mixed proxy port";
          };
          proxyMode = lib.mkOption {
            type = lib.types.enum [
              "rule"
              "whitelist"
              "global"
            ];
            default = defaultConfig.proxyMode;
            description = "Proxy mode";
          };
          runMode = lib.mkOption {
            type = lib.types.enum [
              "fake-ip"
              "redir"
            ];
            default = defaultConfig.runMode;
            description = "Run mode";
          };
          tunEnabled = lib.mkOption {
            type = lib.types.bool;
            default = defaultConfig.tunEnabled;
            description = "Enable TUN mode";
          };
          lanProxy = lib.mkOption {
            type = lib.types.bool;
            default = defaultConfig.lanProxy;
            description = "Proxy LAN";
          };
          ipv6Proxy = lib.mkOption {
            type = lib.types.bool;
            default = defaultConfig.ipv6Proxy;
            description = "Proxy IPv6";
          };
          mihomoPath = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.mihomoPath;
            description = "Mihomo binary path";
          };
          mihomoData = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.mihomoData;
            description = "Mihomo data directory (geoip, geosite)";
          };
          configDir = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.configDir;
            description = "Config directory";
          };
          ossUrl = lib.mkOption {
            type = lib.types.str;
            default = defaultConfig.ossUrl;
            description = "OSS subscription URL";
          };
        };
      };
      default = { };
      description = "Netflow settings";
    };
  };

  config = lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.mihomo ];

    systemd.services.netflow = {
      description = "netflow proxy client";
      wantedBy = [ "multi-user.target" ];
      conflicts = [ "singbox.service" "singbox-backup.service" ];

      serviceConfig = {
        Type = "simple";
        Restart = "always";
        RestartSec = "5";
        # BindPaths 在 systemd 私有 mount namespace 里把构建产物
        # 投射到 /etc/netflow/config.yaml —— 主机文件系统上不出现
        BindPaths = [ "${configFile}:/etc/netflow/config.yaml" ];
        ExecStart = "${cfg.package}/bin/netflow";
      };
    };
  };
}
