{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.netflow;
in
{
  options.services.netflow = {
    enable = lib.mkEnableOption "netflow proxy client";

    package = lib.mkOption {
      type = lib.types.package;
      default = pkgs.netflow;
      description = "Netflow package";
    };

    settings = lib.mkOption {
      type = lib.types.submodule {
        options = {
          apiPort = lib.mkOption {
            type = lib.types.port;
            default = 9091;
            description = "API control port";
          };
          apiSecret = lib.mkOption {
            type = lib.types.str;
            default = "netflow_secret";
            description = "API secret";
          };
          backendPort = lib.mkOption {
            type = lib.types.port;
            default = 9190;
            description = "Backend API port for LuCI frontend";
          };
          redirPort = lib.mkOption {
            type = lib.types.port;
            default = 7892;
            description = "Redir port";
          };
          dnsPort = lib.mkOption {
            type = lib.types.port;
            default = 7874;
            description = "DNS port";
          };
          mixedPort = lib.mkOption {
            type = lib.types.port;
            default = 9050;
            description = "Mixed proxy port";
          };
          proxyMode = lib.mkOption {
            type = lib.types.enum [
              "rule"
              "whitelist"
              "global"
            ];
            default = "global";
            description = "Proxy mode";
          };
          runMode = lib.mkOption {
            type = lib.types.enum [
              "fake-ip"
              "redir"
            ];
            default = "fake-ip";
            description = "Run mode";
          };
          tunEnabled = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Enable TUN mode";
          };
          lanProxy = lib.mkOption {
            type = lib.types.bool;
            default = false;
            description = "Proxy LAN";
          };
          ipv6Proxy = lib.mkOption {
            type = lib.types.bool;
            default = false;
description = "Proxy IPv6";
          };
          mihomoPath = lib.mkOption {
            type = lib.types.str;
            default = "${pkgs.mihomo}/bin/mihomo";
            description = "Mihomo binary path";
          };
          mihomoData = lib.mkOption {
            type = lib.types.str;
            default = "${pkgs.mihomo}/share/mihomo";
            description = "Mihomo data directory (geoip, geosite)";
          };
          configDir = lib.mkOption {
            type = lib.types.str;
            default = "/etc/netflow/config";
            description = "Config directory";
          };
          ossUrl = lib.mkOption {
            type = lib.types.str;
            default = "https://ocdn01.llguangli25o.com:59991/saos/qyt_news.json,https://cdno01.llguanglisf.com/saos/qyt_news.json,https://tcdn.getxlx.com/saos/qyt_news.json,https://apisa.cnossfile.com/saos/qyt_news.json";
            description = "OSS subscription URL";
          };
        };
      };
      default = { };
      description = "Netflow settings";
    };
  };

  config = let
    configFile = pkgs.writeText "netflow-config.yaml" (''
      # netflow config - generated by NixOS module
      port: ${builtins.toString cfg.settings.backendPort}
      secret: "${cfg.settings.apiSecret}"
      redirPort: ${builtins.toString cfg.settings.redirPort}
      dnsPort: ${builtins.toString cfg.settings.dnsPort}
      mixedPort: ${builtins.toString cfg.settings.mixedPort}
      proxyMode: ${cfg.settings.proxyMode}
      runMode: ${cfg.settings.runMode}
      tunEnabled: ${if cfg.settings.tunEnabled then "true" else "false"}
      lanProxy: ${if cfg.settings.lanProxy then "true" else "false"}
      ipv6Proxy: ${if cfg.settings.ipv6Proxy then "true" else "false"}
      mihomoPath: ${cfg.settings.mihomoPath}
      mihomoData: ${cfg.settings.mihomoData}
      configDir: ${cfg.settings.configDir}
      ossUrl: "${cfg.settings.ossUrl}"
    '');
  in
  lib.mkIf cfg.enable {
    environment.systemPackages = [ pkgs.mihomo ];

    systemd.services.netflow = {
      description = "netflow proxy client";
      wantedBy = [ "multi-user.target" ];
      conflicts = [ "singbox.service" "singbox-backup.service" ];

      serviceConfig = {
        Type = "simple";
        Restart = "always";
        RestartSec = "5";
        # BindPaths 在 systemd 私有 mount namespace 里把构建产物
        # 投射到 /etc/netflow/config.yaml —— 主机文件系统上不出现
        BindPaths = [ "${configFile}:/etc/netflow/config.yaml" ];
        ExecStart = "${cfg.package}/bin/netflow";
      };
    };
  };
}
